---
title: "Cytosel report"
output: 
  html_document:
    toc: true
    toc_float: true
params:
  df: ""
  marker_selection: ""
  heatmap: ""
  umap: ""
  metric: ""
  config: ""
  tmpdir: ""
---

<style>
.main-container {
    max-width: 940px;
    margin-right: auto;
}
</style>

Below are the results of your Cytosel antibody panel design run.

```{r message=FALSE, echo=F}
knitr::opts_knit$set(root.dir = params$tmpdir)
library(tidyverse)
library(DT)
library(yaml)
library(shiny)
library(printr)
library(reactable)
```

## Antibody panel

```{r message=F, echo=F}
# ab <- read_tsv(params$df)
ab <- params$df
reactable(ab,
                searchable = TRUE,
                filterable = TRUE,
                columns = list(`Host Species` = colDef(
                  filterInput = function(values, name) {
                    tags$select(
                      # Set to undefined to clear the filter
                      onchange = sprintf("Reactable.setFilter('antibody-select', '%s', event.target.value || undefined)", name),
                      # "All" has an empty value to clear the filter, and is the default option
                      tags$option(value = "", "All"),
                      lapply(unique(values), tags$option),
                      "aria-label" = sprintf("Filter %s", name),
                      style = "width: 100%; height: 28px;"
                    )
                  }
                ),
                `Product Category Tier 3` = colDef(
                  filterInput = function(values, name) {
                    tags$select(
                      # Set to undefined to clear the filter
                      onchange = sprintf("Reactable.setFilter('antibody-select', '%s', event.target.value || undefined)", name),
                      # "All" has an empty value to clear the filter, and is the default option
                      tags$option(value = "", "All"),
                      lapply(unique(values), tags$option),
                      "aria-label" = sprintf("Filter %s", name),
                      style = "width: 100%; height: 28px;"
                    )
                  }
                ),
                `External Link` = colDef(html = T)
                ),
                sortable = TRUE,
                elementId = "antibody-select")
```

## Selected markers

You selected the following markers to be included in your antibody panel.

```{r message=FALSE, echo=F, results = 'asis'}
# markers <- readLines(params$marker_selection)
markers <- params$marker_selection
cat(paste0("- `", markers, "`"), sep = "\n")
```

## Heatmaps

```{r echo=F, warning=F}
# heatmap <- readRDS(params$heatmap)
heatmap
```

## UMAPs

```{r echo = F, fig.width=8, fig.height=5}
# umaps <- readRDS(params$umap)
umaps <- params$umap
umaps
```

## Metrics {.tabset}

### Distribution

```{r echo=F, warning=F, fig.width=10}
# metrics <- readRDS(params$metric)
metrics <- params$metric
metrics$plot
```


### Summary table

```{r echo=F, warning=F, fig.width=10}
metrics$table |> 
  datatable(options = list(autoWidth = FALSE))
```


## Config

Below is the configuration used during your run:

```{r echo = F,message=F}
# config <- read_tsv(params$config)
config <- params$config
config |> 
  datatable(options = list(autoWidth = FALSE))
```
