name: test-package
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-test-that:
    runs-on:
      labels: ubuntu-20.04-16core
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install cURL Headers
        run: |
         sudo apt-get update
         sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libgeos-dev
# name: Install required packages not listed in the package description
# run: |
# install.packages(c("BiocManager", "caret", "Seurat", "tidyverse"))
# BiocManager::install(version = "3.16")
# BiocManager::install(c('scran', 'scuttle', 'scater'))
# shell: Rscript {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
