name: test-package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-test-that:
    runs-on: ubuntu-latest
    env:
      R_TESTS_VERBOSE: 2
      MSYS: winsymlinks:nativestrict
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install cURL Headers
        run: |
         sudo apt-get update
         sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libgeos-dev
        shell: bash -l {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
