on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: shiny-deploy

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}

      - name: Install BiocManager
        run: install.packages("BiocManager")
        shell: Rscript {0}

      - name: Authorize and deploy app
        env: 
          APPNAME: cytosel
          ACCOUNT: camlab
          SERVER: shinyapps.io
        run: |
          options(repos=c(BiocManager::repositories()))
          rsconnect::setAccountInfo(name='camlab', token='96CDA60CB4F4AB671D836E7E0CF6E77A', secret='PZxUCJz2m9bL4Mj5GPL+zjdGNm4DWbToKdjOWK57')
          rsconnect::deployApp(appName = "${{ env.APPNAME }}", account = "${{ env.ACCOUNT }}", server = "${{ env.SERVER }}")
        shell: Rscript {0}
