name: deploy cytosel to shinyapps.io
on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy cytosel to shinyapps.io
      - run: R -e 'rsconnect::setAccountInfo(name='camlab', token='***REMOVED***', secret='***REMOVED***')'
      - run: Rscript deploy.R
